# Generated by Django 5.2.14 on 2026-05-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-acted_at'],
                'indexes': [models.Index(fields=['acted_at'], name='core_auditl_acted_a_dfd9f9_idx'), models.Index(fields=['actor'], name='core_auditl_actor_71715a_idx'), models.Index(fields=['target_type'], name='core_auditl_target__5a1607_idx'), models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx')],
            },
        ),
    ]
