# Generated by Django 5.2.14 on 2026-05-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('system_type', models.CharField(choices=[('groupware', '그룹웨어'), ('erp', 'ERP'), ('fileserver-account', '파일서버 계정'), ('fileserver-folder', '파일서버 폴더'), ('firewall', '방화벽')], max_length=30)),
                ('work_type', models.CharField(choices=[('add', '추가'), ('delete', '삭제'), ('leave', '퇴사처리'), ('permission', '권한변경'), ('folder-create', '폴더 생성'), ('folder-rename', '폴더명 변경')], max_length=30)),
                ('operator', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['work_date'], name='accounts_wo_work_da_8116c7_idx'), models.Index(fields=['system_type'], name='accounts_wo_system__c65c89_idx'), models.Index(fields=['work_type'], name='accounts_wo_work_ty_448338_idx'), models.Index(fields=['operator'], name='accounts_wo_operato_028ed7_idx'), models.Index(fields=['target'], name='accounts_wo_target_9c3653_idx')],
            },
        ),
    ]
