# Generated by Django 5.2.14 on 2026-05-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IpGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_group_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(blank=True, max_length=100)),
                ('is_phone_group', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['parent_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('high_dept_code', models.CharField(blank=True, max_length=20)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('view_order', models.IntegerField(blank=True, null=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.company')),
            ],
            options={
                'ordering': ['view_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('ip_int', models.BigIntegerField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('start_date', models.CharField(blank=True, max_length=20)),
                ('end_date', models.CharField(blank=True, max_length=20)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ipgroup')),
            ],
            options={
                'ordering': ['ip_int'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('mac', models.CharField(blank=True, db_index=True, max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('division', models.CharField(blank=True, max_length=100)),
                ('scan_user', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ipaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('employee', '임직원'), ('other', '기타')], max_length=10)),
                ('legacy_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('emp_no', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('hp', models.CharField(blank=True, max_length=50)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
                ('resign_dt', models.CharField(blank=True, max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.department')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('person_type', 'legacy_id')},
            },
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.person'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_id', models.CharField(max_length=20, unique=True)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('start_date', models.CharField(blank=True, max_length=20)),
                ('end_date', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ipaddress')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.person')),
            ],
            options={
                'ordering': ['phone_id'],
            },
        ),
    ]
