# Generated by Django 5.2.14 on 2026-05-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspect_ym', models.CharField(max_length=7, unique=True)),
                ('created_by', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-inspect_ym'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('excel_label', models.CharField(blank=True, max_length=50)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('registered_ip', models.CharField(blank=True, max_length=45)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('collect_method', models.CharField(choices=[('manual', '수동'), ('db-view', 'DB View'), ('winrm', 'WinRM'), ('ssh', 'SSH'), ('api', 'API')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_status', models.CharField(blank=True, max_length=50)),
                ('ip_detected', models.CharField(blank=True, max_length=45)),
                ('event_log_summary', models.TextField(blank=True)),
                ('event_critical', models.IntegerField(blank=True, null=True)),
                ('event_error', models.IntegerField(blank=True, null=True)),
                ('event_warning', models.IntegerField(blank=True, null=True)),
                ('cpu_total_ghz', models.FloatField(blank=True, null=True)),
                ('cpu_usage_pct', models.FloatField(blank=True, null=True)),
                ('ram_total_gb', models.FloatField(blank=True, null=True)),
                ('ram_used_gb', models.FloatField(blank=True, null=True)),
                ('disk_info_json', models.TextField(blank=True)),
                ('disk_health', models.CharField(blank=True, max_length=100)),
                ('last_backup_date', models.DateField(blank=True, null=True)),
                ('win_update_status', models.CharField(blank=True, max_length=100)),
                ('v3_version', models.CharField(blank=True, max_length=100)),
                ('account_create_cnt', models.IntegerField(blank=True, null=True)),
                ('account_change_cnt', models.IntegerField(blank=True, null=True)),
                ('account_delete_cnt', models.IntegerField(blank=True, null=True)),
                ('ips_block_cnt', models.IntegerField(blank=True, null=True)),
                ('ips_attempt_cnt', models.IntegerField(blank=True, null=True)),
                ('mail_normal_cnt', models.IntegerField(blank=True, null=True)),
                ('mail_spam_cnt', models.IntegerField(blank=True, null=True)),
                ('mail_virus_cnt', models.IntegerField(blank=True, null=True)),
                ('mail_ransom_cnt', models.IntegerField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_collected', models.BooleanField(default=False)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inspection.inspection')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.server')),
            ],
            options={
                'unique_together': {('inspection', 'server')},
            },
        ),
    ]
