# Generated by Django 5.2.14 on 2026-05-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_rack_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_switch_id', models.IntegerField(unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('sort_order', models.IntegerField(default=0)),
                ('vendor', models.CharField(default='juniper', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='switches.rack')),
            ],
            options={
                'ordering': ['rack__name', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SwitchConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_data', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('backup_date', models.CharField(blank=True, max_length=20)),
                ('backup_time', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='switches.switch')),
            ],
            options={
                'ordering': ['-backup_date', '-backup_time'],
                'indexes': [models.Index(fields=['switch', 'backup_date', 'backup_time'], name='switches_sw_switch__744432_idx'), models.Index(fields=['backup_date', 'backup_time'], name='switches_sw_backup__65a809_idx')],
            },
        ),
        migrations.CreateModel(
            name='SwitchMacEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=50)),
                ('vlan', models.CharField(blank=True, max_length=20)),
                ('mac', models.CharField(db_index=True, max_length=20)),
                ('entry_type', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_entries', to='switches.switch')),
            ],
            options={
                'indexes': [models.Index(fields=['mac'], name='switches_sw_mac_eed43b_idx'), models.Index(fields=['switch', 'interface'], name='switches_sw_switch__231f1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SwitchPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=50)),
                ('port_mode', models.CharField(blank=True, max_length=20)),
                ('area_number', models.CharField(blank=True, max_length=20)),
                ('port_number', models.CharField(blank=True, max_length=20)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='switches.switch')),
            ],
            options={
                'ordering': ['switch', 'interface'],
                'unique_together': {('switch', 'interface')},
            },
        ),
    ]
