# Generated by Django 5.2.14 on 2026-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchport',
            name='area_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='switchport',
            name='port_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
